parameters:
    opifer.content.document_block.class: Opifer\ContentBundle\Block\DocumentBlockService
    opifer.content.html_block.class: Opifer\ContentBundle\Block\HtmlBlockService
    opifer.content.image_block.class: Opifer\ContentBundle\Block\ImageBlockService
    opifer.content.jumbotron_block.class: Opifer\ContentBundle\Block\JumbotronBlockService
    opifer.content.jumbotron_block.styles: ["jumbotron-sm", "jumbotron-lg", "text-regular", "text-contrast"]
    opifer.content.button_block.class: Opifer\ContentBundle\Block\ButtonBlockService
    opifer.content.button_block.styles: ["btn-sm", "btn-lg", "btn-primary", "btn-default", "btn-block", "center-block"]
#    opifer.content.image_gallery_block.class: Opifer\ContentBundle\Block\ImageGalleryBlockService
#    opifer.content.list_block.class: Opifer\ContentBundle\Block\ListBlockService
    opifer.content.layout_block.class: Opifer\ContentBundle\Block\LayoutBlockService
    opifer.content.container_block.class: Opifer\ContentBundle\Block\ContainerBlockService
    opifer.content.column_block.class: Opifer\ContentBundle\Block\ColumnBlockService

services:
    opifer.content.html_block:
        class: %opifer.content.html_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: html }

    opifer.content.image_block:
        class: %opifer.content.image_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: image }

    opifer.content.jumbotron_block:
        class: %opifer.content.jumbotron_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: jumbotron }
        calls:
            - [setStyles, [%opifer.content.jumbotron_block.styles%]]

    opifer.content.button_block:
        class: %opifer.content.button_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: button }
        calls:
            - [setStyles, [%opifer.content.button_block.styles%]]

    opifer.content.container_section_block:
        class: %opifer.content.container_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: container_section }
        calls:
            - [setWrapper, ["section"]]

    opifer.content.container_block:
        class: %opifer.content.container_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: container_container }
        calls:
            - [setWrapper, ["container"]]

    opifer.content.column_one_block:
        class: %opifer.content.column_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: column_one }
        calls:
            - [setColumnCount, [1]]

    opifer.content.column_two_block:
        class: %opifer.content.column_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: column_two }
        calls:
            - [setColumnCount, [2]]

    opifer.content.column_three_block:
        class: %opifer.content.column_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: column_three }
        calls:
            - [setColumnCount, [3]]

    opifer.content.column_four_block:
        class: %opifer.content.column_block.class%
        arguments: [@templating]
        tags:
            - { name: opifer.content.block_service, alias: column_four }
        calls:
            - [setColumnCount, [4]]