parameters:
    opifer.content.button_block.class: Opifer\ContentBundle\Block\Service\ButtonBlockService
    opifer.content.carousel_block.class: Opifer\ContentBundle\Block\Service\CarouselBlockService
    opifer.content.carousel_slide_block.class: Opifer\ContentBundle\Block\Service\CarouselSlideBlockService
    opifer.content.collection_block.class: Opifer\ContentBundle\Block\Service\CollectionBlockService
    opifer.content.column_block.class: Opifer\ContentBundle\Block\Service\ColumnBlockService
    opifer.content.container_block.class: Opifer\ContentBundle\Block\Service\ContainerBlockService
    opifer.content.html_block.class: Opifer\ContentBundle\Block\Service\HtmlBlockService
    opifer.content.image_block.class: Opifer\ContentBundle\Block\Service\ImageBlockService
    opifer.content.jumbotron_block.class: Opifer\ContentBundle\Block\Service\JumbotronBlockService
    opifer.content.pointer_block.class: Opifer\ContentBundle\Block\Service\PointerBlockService
    opifer.content.list_block.class: Opifer\ContentBundle\Block\Service\ListBlockService
#    opifer.content.image_gallery_block.class: Opifer\ContentBundle\Block\ImageGalleryBlockService

services:
    opifer.content.carousel_block:
        class: '%opifer.content.carousel_block.class%'
        arguments: ['@templating', '%opifer_content.carousel_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: carousel }

    opifer.content.carousel_slide_block:
        class: '%opifer.content.carousel_slide_block.class%'
        arguments: ['@templating', '%opifer_content.carousel_slide_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: carousel_slide }

    opifer.content.collection_block:
        class: '%opifer.content.collection_block.class%'
        arguments: ['@templating', '@opifer.content.content_manager', '%opifer_content.collection_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: collection }

    opifer.content.html_block:
        class: '%opifer.content.html_block.class%'
        arguments: ['@templating', '%opifer_content.html_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: html }

    opifer.content.image_block:
        class: '%opifer.content.image_block.class%'
        arguments: ['@templating', '%liip_imagine.filter_sets%', '%opifer_content.image_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: image }

    opifer.content.list_block:
        class: '%opifer.content.list_block.class%'
        arguments: ['@templating', '@opifer.content.content_manager', '%opifer_content.list_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: list }

    opifer.content.jumbotron_block:
        class: '%opifer.content.jumbotron_block.class%'
        arguments: ['@templating', '%opifer_content.jumbotron_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: jumbotron }

    opifer.content.button_block:
        class: '%opifer.content.button_block.class%'
        arguments: ['@templating', '%opifer_content.button_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: button }

    opifer.content.pointer_block:
        class: '%opifer.content.pointer_block.class%'
        arguments: ['@templating', '@opifer.content.block_manager', '%opifer_content.pointer_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: pointer }

    opifer.content.container_section_block:
        class: '%opifer.content.container_block.class%'
        arguments: ['@templating', '%opifer_content.container_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: container_section }
        calls:
            - [setWrapper, ["section"]]

    opifer.content.container_block:
        class: '%opifer.content.container_block.class%'
        arguments: ['@templating', '%opifer_content.container_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: container_container }
        calls:
            - [setWrapper, ["container"]]

    opifer.content.column_one_block:
        class: '%opifer.content.column_block.class%'
        arguments: ['@templating', '%opifer_content.column_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: column_one }
        calls:
            - [setColumnCount, [1]]

    opifer.content.column_two_block:
        class: '%opifer.content.column_block.class%'
        arguments: ['@templating', '%opifer_content.column_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: column_two }
        calls:
            - [setColumnCount, [2]]

    opifer.content.column_three_block:
        class: '%opifer.content.column_block.class%'
        arguments: ['@templating', '%opifer_content.column_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: column_three }
        calls:
            - [setColumnCount, [3]]

    opifer.content.column_four_block:
        class: '%opifer.content.column_block.class%'
        arguments: ['@templating', '%opifer_content.column_block_configuration%']
        tags:
            - { name: opifer.content.block_service, alias: column_four }
        calls:
            - [setColumnCount, [4]]
