opifer_content_formtype_angular:
    path: /formtype/angular
    defaults: { _controller: OpiferContentBundle:Backend/FormType:angular }
    options:
        expose: true

# Backend Directory
opifer_content_directory_index:
    path: /directory
    defaults: { _controller: OpiferContentBundle:Backend/Directory:index }

opifer_content_directory_new:
    path: /directory/new
    defaults: { _controller: OpiferContentBundle:Backend/Directory:new }

opifer_content_directory_edit:
    path: /directory/edit/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Directory:edit }

opifer_content_directory_delete:
    path: /directory/delete/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Directory:delete }

opifer_content_template_index:
    path: /template
    defaults: { _controller: OpiferContentBundle:Backend/Template:index }

opifer_content_template_editor:
    path: /template/editor/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Template:editor }

opifer_content_template_editor_view:
    path: /template/editor/view/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Template:editorView }

# Backend content
opifer_content_content_new:
    path: /content/new/{schema}/{mode}
    defaults: { _controller: OpiferContentBundle:Backend/Content:new, schema: 0, mode: simple }

opifer_content_content_details:
    path: /content/details/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Content:details, id: 0 }
    options:
        expose: true

opifer_content_content_duplicate:
    path: /content/duplicate/{id}
    defaults: { _controller: OpiferContentBundle:Backend/Content:duplicate }
    options:
        expose: true

opifer_content_content_index:
    path: /content/{directoryId}
    defaults: { _controller: OpiferContentBundle:Backend/Content:index, directoryId: 0 }
    requirements:
        directoryId:  \d+

opifer_content_content_history:
    path: /content/history/{type}/{id}/{version}
    defaults: { _controller: OpiferContentBundle:Backend/Content:history, version: 0 }
    options:
        expose: true

# Contenteditor
opifer_content_contenteditor_design:
    path: /designer/{type}/{id}/{rootVersion}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:design, rootVersion: 0 }
    options:
        expose: true

opifer_content_contenteditor_edit_block:
    path: /contenteditor/editblock/{id}/{rootVersion}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:editBlock, rootVersion: 0 }
    options:
        expose: true

opifer_content_contenteditor_version_picker:
    path: /contenteditor/versionpicker/{id}/{current}/{published}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:versionPicker, current: 0, published: 0 }
    options:
        expose: true

opifer_content_contenteditor_view:
    path: /contenteditor/view/{type}/{id}/{version}
    defaults: { _controller: OpiferContentBundle:Backend/ContentEditor:view, version: 0 }
    options:
        expose: true